[2023-09-15T12:17:04.912+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: business_question.daily_earnings manual__2023-09-15T12:16:59.857558+00:00 [queued]>
[2023-09-15T12:17:04.931+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: business_question.daily_earnings manual__2023-09-15T12:16:59.857558+00:00 [queued]>
[2023-09-15T12:17:04.932+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2023-09-15T12:17:04.957+0000] {taskinstance.py:1350} INFO - Executing <Task(GenericTransfer): daily_earnings> on 2023-09-15 12:16:59.857558+00:00
[2023-09-15T12:17:04.974+0000] {standard_task_runner.py:57} INFO - Started process 1633 to run task
[2023-09-15T12:17:05.010+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'business_question', 'daily_earnings', 'manual__2023-09-15T12:16:59.857558+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/businesse.py', '--cfg-path', '/tmp/tmpxwnrq5ie']
[2023-09-15T12:17:05.034+0000] {standard_task_runner.py:85} INFO - Job 11: Subtask daily_earnings
[2023-09-15T12:17:05.443+0000] {task_command.py:410} INFO - Running <TaskInstance: business_question.daily_earnings manual__2023-09-15T12:16:59.857558+00:00 [running]> on host 7b2f04a25b74
[2023-09-15T12:17:05.808+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Aldinoharyo' AIRFLOW_CTX_DAG_ID='business_question' AIRFLOW_CTX_TASK_ID='daily_earnings' AIRFLOW_CTX_EXECUTION_DATE='2023-09-15T12:16:59.857558+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-15T12:16:59.857558+00:00'
[2023-09-15T12:17:05.845+0000] {base.py:73} INFO - Using connection ID 'destination' for task execution.
[2023-09-15T12:17:05.966+0000] {base.py:73} INFO - Using connection ID 'final_destination' for task execution.
[2023-09-15T12:17:06.018+0000] {generic_transfer.py:77} INFO - Extracting data from destination
[2023-09-15T12:17:06.018+0000] {generic_transfer.py:78} INFO - Executing: 
 
    SELECT SUM("DailyEarnings") as "TotalEarning"
    FROM (
            SELECT "InvoiceDate", SUM("TotalPrice") as "DailyEarnings"
            FROM "revenue"
            GROUP BY "InvoiceDate"
    ) as a
    
[2023-09-15T12:17:06.051+0000] {base.py:73} INFO - Using connection ID 'destination' for task execution.
[2023-09-15T12:17:06.059+0000] {sql.py:375} INFO - Running statement: 
    SELECT SUM("DailyEarnings") as "TotalEarning"
    FROM (
            SELECT "InvoiceDate", SUM("TotalPrice") as "DailyEarnings"
            FROM "revenue"
            GROUP BY "InvoiceDate"
    ) as a
    , parameters: None
[2023-09-15T12:17:06.061+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/generic_transfer.py", line 86, in execute
    results = get_records(self.sql)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 235, in get_records
    return self.run(sql=sql, parameters=parameters, handler=fetch_all_handler)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedTable: relation "revenue" does not exist
LINE 5:             FROM "revenue"
                         ^

[2023-09-15T12:17:06.101+0000] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=business_question, task_id=daily_earnings, execution_date=20230915T121659, start_date=20230915T121704, end_date=20230915T121706
[2023-09-15T12:17:06.127+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 11 for task daily_earnings (relation "revenue" does not exist
LINE 5:             FROM "revenue"
                         ^
; 1633)
[2023-09-15T12:17:06.146+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-09-15T12:17:06.180+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
