[2023-09-15T12:15:37.873+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: business_question.daily_earnings manual__2023-09-15T12:15:34.774407+00:00 [queued]>
[2023-09-15T12:15:37.887+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: business_question.daily_earnings manual__2023-09-15T12:15:34.774407+00:00 [queued]>
[2023-09-15T12:15:37.889+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2023-09-15T12:15:37.911+0000] {taskinstance.py:1350} INFO - Executing <Task(GenericTransfer): daily_earnings> on 2023-09-15 12:15:34.774407+00:00
[2023-09-15T12:15:37.918+0000] {standard_task_runner.py:57} INFO - Started process 1612 to run task
[2023-09-15T12:15:37.925+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'business_question', 'daily_earnings', 'manual__2023-09-15T12:15:34.774407+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/businesse.py', '--cfg-path', '/tmp/tmpx_h7c58k']
[2023-09-15T12:15:37.930+0000] {standard_task_runner.py:85} INFO - Job 10: Subtask daily_earnings
[2023-09-15T12:15:38.015+0000] {task_command.py:410} INFO - Running <TaskInstance: business_question.daily_earnings manual__2023-09-15T12:15:34.774407+00:00 [running]> on host 7b2f04a25b74
[2023-09-15T12:15:38.198+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Aldinoharyo' AIRFLOW_CTX_DAG_ID='business_question' AIRFLOW_CTX_TASK_ID='daily_earnings' AIRFLOW_CTX_EXECUTION_DATE='2023-09-15T12:15:34.774407+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-15T12:15:34.774407+00:00'
[2023-09-15T12:15:38.214+0000] {base.py:73} INFO - Using connection ID 'destination' for task execution.
[2023-09-15T12:15:38.323+0000] {base.py:73} INFO - Using connection ID 'final_destination' for task execution.
[2023-09-15T12:15:38.410+0000] {generic_transfer.py:77} INFO - Extracting data from destination
[2023-09-15T12:15:38.411+0000] {generic_transfer.py:78} INFO - Executing: 
 
    SELECT SUM("DailyEarnings") as "TotalEarning"
    FROM (
            SELECT "InvoiceDate", SUM("TotalPrice") as "DailyEarnings"
            FROM "artist_revenue"
            GROUP BY "InvoiceDate"
    ) as a
    
[2023-09-15T12:15:38.422+0000] {base.py:73} INFO - Using connection ID 'destination' for task execution.
[2023-09-15T12:15:38.428+0000] {sql.py:375} INFO - Running statement: 
    SELECT SUM("DailyEarnings") as "TotalEarning"
    FROM (
            SELECT "InvoiceDate", SUM("TotalPrice") as "DailyEarnings"
            FROM "artist_revenue"
            GROUP BY "InvoiceDate"
    ) as a
    , parameters: None
[2023-09-15T12:15:38.443+0000] {sql.py:384} INFO - Rows affected: 1
[2023-09-15T12:15:38.444+0000] {generic_transfer.py:95} INFO - Running preoperator
[2023-09-15T12:15:38.445+0000] {generic_transfer.py:96} INFO - ['DROP TABLE IF EXISTS question1', '\n        CREATE TABLE question1 (\n        \n        "InvoiceDate" TIMESTAMP NOT NULL,\n        "DailyEarnings" NUMERIC(10,2) NOT NULL\n    \n        )\n        ']
[2023-09-15T12:15:38.456+0000] {base.py:73} INFO - Using connection ID 'final_destination' for task execution.
[2023-09-15T12:15:38.462+0000] {sql.py:375} INFO - Running statement: DROP TABLE IF EXISTS question1, parameters: None
[2023-09-15T12:15:38.467+0000] {sql.py:375} INFO - Running statement: 
        CREATE TABLE question1 (
        
        "InvoiceDate" TIMESTAMP NOT NULL,
        "DailyEarnings" NUMERIC(10,2) NOT NULL
    
        )
        , parameters: None
[2023-09-15T12:15:38.476+0000] {generic_transfer.py:105} INFO - Inserting rows into final_destination
[2023-09-15T12:15:38.486+0000] {base.py:73} INFO - Using connection ID 'final_destination' for task execution.
[2023-09-15T12:15:38.492+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/generic_transfer.py", line 106, in execute
    insert_rows(table=self.destination_table, rows=results, **self.insert_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 467, in insert_rows
    cur.execute(sql, values)
psycopg2.errors.DatatypeMismatch: column "InvoiceDate" is of type timestamp without time zone but expression is of type numeric
LINE 1: INSERT INTO question1  VALUES (2328.60)
                                       ^
HINT:  You will need to rewrite or cast the expression.

[2023-09-15T12:15:38.512+0000] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=business_question, task_id=daily_earnings, execution_date=20230915T121534, start_date=20230915T121537, end_date=20230915T121538
[2023-09-15T12:15:38.529+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 10 for task daily_earnings (column "InvoiceDate" is of type timestamp without time zone but expression is of type numeric
LINE 1: INSERT INTO question1  VALUES (2328.60)
                                       ^
HINT:  You will need to rewrite or cast the expression.
; 1612)
[2023-09-15T12:15:38.577+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-09-15T12:15:38.640+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
